"""Add menu_id property

Revision ID: 087a6ccdb4c5
Revises: 4f5333aff7fb
Create Date: 2020-02-28 09:05:22.382095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087a6ccdb4c5'
down_revision = '4f5333aff7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderitem', sa.Column('menu_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderitem', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_column('orderitem', 'menu_id')
    # ### end Alembic commands ###
