"""Fix relationship method parameters

Revision ID: 281184100232
Revises: d1d28e59ec92
Create Date: 2020-02-26 22:36:35.978875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281184100232'
down_revision = 'd1d28e59ec92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
