"""Add serialization to order table

Revision ID: 2e08a175fbf1
Revises: 281184100232
Create Date: 2020-02-26 22:39:01.726588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e08a175fbf1'
down_revision = '281184100232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
