"""Add serialization to OrderItem

Revision ID: 4f5333aff7fb
Revises: 2e08a175fbf1
Create Date: 2020-02-28 02:52:52.291828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5333aff7fb'
down_revision = '2e08a175fbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
