"""empty message

Revision ID: 74448b5d183c
Revises: 34248b9d74ce
Create Date: 2020-02-11 19:58:27.574027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74448b5d183c'
down_revision = '34248b9d74ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
