"""add student table

Revision ID: 7f945b076972
Revises: a1c4470e4dea
Create Date: 2020-02-20 00:10:14.144544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f945b076972'
down_revision = 'a1c4470e4dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
