"""Fix menu active property

Revision ID: a1c4470e4dea
Revises: 418303f5238e
Create Date: 2020-02-14 02:13:24.198885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c4470e4dea'
down_revision = '418303f5238e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
