"""add order table

Revision ID: c70252623c34
Revises: 7f945b076972
Create Date: 2020-02-24 17:00:21.541512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70252623c34'
down_revision = '7f945b076972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('student_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_no'], ['student.student_no'], ),
    sa.PrimaryKeyConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
