"""Make order_item_no explicit in autoincrement

Revision ID: d37d90425000
Revises: 087a6ccdb4c5
Create Date: 2020-02-28 09:07:26.440168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37d90425000'
down_revision = '087a6ccdb4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
